### ISSUE TITLE
Set tabsize to 4

### ISSUE THREAD

**Issue by ernstla** [vacantplanet/mkdocs-theme#1]
Set the tabsize in `pre` blocks to 4.

```css
pre {
    tabsize: 4;
}
```
